data {
  id: 'ch_3RdvGjQ4lBhBuMOJ148WI5L5',
  object: 'charge',
  amount: 2900,
  amount_captured: 2900,
  amount_refunded: 0,
  application: null,
  application_fee: null,
  application_fee_amount: null,     
  balance_transaction: null,        
  billing_details: {
    address: {
      city: null,
      country: 'KR',
      line1: null,
      line2: null,
      postal_code: null,
      state: null
    },
    email: 'johndoeyyd@gmail.com',
    name: 'dwdwdw dwadwad',
    phone: null,
    tax_id: null
  },
  calculated_statement_descriptor: 'Stripe',
  captured: true,
  created: 1750865390,
  currency: 'usd',
  customer: 'cus_SZ2WYe5AWaVGKF',
  description: null,
  destination: null,
  dispute: null,
  disputed: false,
  failure_balance_transaction: null,
  failure_code: null,
  failure_message: null,
  fraud_details: {},
  livemode: false,
  metadata: {},
  on_behalf_of: null,
  order: null,
  outcome: {
    advice_code: null,
    network_advice_code: null,
    network_decline_code: null,
    network_status: 'approved_by_network',
    reason: null,
    risk_level: 'normal',
    risk_score: 35,
    seller_message: 'Payment complete.',
    type: 'authorized'
  },
  paid: true,
  payment_intent: 'pi_3RdvGjQ4lBhBuMOJ1ayQ7JqW',
  payment_method: 'pm_1RdvGjQ4lBhBuMOJvsdwOzbD',
  payment_method_details: {
    card: {
      amount_authorized: 2900,
      authorization_code: '549879',
      brand: 'visa',
      checks: [Object],
      country: 'US',
      exp_month: 6,
      exp_year: 2028,
      extended_authorization: [Object],
      fingerprint: '4SGERArAYrxykaph',
      funding: 'credit',
      incremental_authorization: [Object],
      installments: null,
      last4: '4242',
      mandate: null,
      multicapture: [Object],
      network: 'visa',
      network_token: [Object],
      network_transaction_id: '528371698265114',
      overcapture: [Object],
      regulated_status: 'unregulated',
      three_d_secure: null,
      wallet: null
    },
    type: 'card'
  },
  presentment_details: { presentment_amount: 41138, presentment_currency: 'krw' },      
  radar_options: {},
  receipt_email: null,
  receipt_number: null,
  receipt_url: 'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xUmRzS1VRNGxCaEJ1TU9KKO-r8MIGMgbUAv1iMho6LBacTz7XWzIDmn-Ru2LB8Aj4EbgQC4VAAAXIp95f_y-eGgOAgeTVxyuQaIe6',  
  refunded: false,
  review: null,
  shipping: null,
  source: null,
  source_transfer: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: 'succeeded',
  transfer_data: null,
  transfer_group: null
}
eventType charge.succeeded
data {
  id: 'pi_3RdvGjQ4lBhBuMOJ1ayQ7JqW',
  object: 'payment_intent',
  amount: 2900,
  amount_capturable: 0,
  amount_details: { tip: {} },
  amount_received: 2900,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: null,
  cancellation_reason: null,
  capture_method: 'automatic_async',
  client_secret: 'pi_3RdvGjQ4lBhBuMOJ1ayQ7JqW_secret_FXxHKFc18REreb1hOqqfOHcew',        
  confirmation_method: 'automatic',
  created: 1750865389,
  currency: 'usd',
  customer: 'cus_SZ2WYe5AWaVGKF',
  description: null,
  last_payment_error: null,
  latest_charge: 'ch_3RdvGjQ4lBhBuMOJ148WI5L5',
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: 'pm_1RdvGjQ4lBhBuMOJvsdwOzbD',
  payment_method_configuration_details: null,
  payment_method_options: {
    card: {
      installments: null,
      mandate_options: null,
      network: null,
      request_three_d_secure: 'automatic'
    }
  },
  payment_method_types: [ 'card' ],
  presentment_details: { presentment_amount: 41138, presentment_currency: 'krw' },      
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: null,
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: 'succeeded',
  transfer_data: null,
  transfer_group: null
}
eventType payment_intent.succeeded
data {
  id: 'pi_3RdvGjQ4lBhBuMOJ1ayQ7JqW',
  object: 'payment_intent',
  amount: 2900,
  amount_capturable: 0,
  amount_details: { tip: {} },
  amount_received: 0,
  application: null,
  application_fee_amount: null,
  automatic_payment_methods: null,
  canceled_at: null,
  cancellation_reason: null,
  capture_method: 'automatic_async',
  client_secret: 'pi_3RdvGjQ4lBhBuMOJ1ayQ7JqW_secret_FXxHKFc18REreb1hOqqfOHcew',        
  confirmation_method: 'automatic',
  created: 1750865389,
  currency: 'usd',
  customer: 'cus_SZ2WYe5AWaVGKF',
  description: null,
  last_payment_error: null,
  latest_charge: null,
  livemode: false,
  metadata: {},
  next_action: null,
  on_behalf_of: null,
  payment_method: null,
  payment_method_configuration_details: null,
  payment_method_options: {
    card: {
      installments: null,
      mandate_options: null,
      network: null,
      request_three_d_secure: 'automatic'
    }
  },
  payment_method_types: [ 'card' ],
  presentment_details: { presentment_amount: 41138, presentment_currency: 'krw' },      
  processing: null,
  receipt_email: null,
  review: null,
  setup_future_usage: null,
  shipping: null,
  source: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: 'requires_payment_method',
  transfer_data: null,
  transfer_group: null
}
eventType payment_intent.created
data {
  id: 'cs_test_a1fBzMEMPTFBp9EZkMIWvT0zvFjZzNv8QWif0Se78KU72Yk19OwvMb2stM',
  object: 'checkout.session',
  adaptive_pricing: { enabled: true },
  after_expiration: null,
  allow_promotion_codes: null,
  amount_subtotal: 2900,
  amount_total: 2900,
  automatic_tax: { enabled: false, liability: null, provider: null, status: null },     
  billing_address_collection: null,
  cancel_url: 'http://localhost:3000/cancel?productId=685c01e14eeb8092e7300640&userId=685c096468359b1216cb3d8b',
  client_reference_id: null,
  client_secret: null,
  collected_information: { shipping_details: null },
  consent: null,
  consent_collection: null,
  created: 1750865371,
  currency: 'usd',
  currency_conversion: null,
  custom_fields: [],
  custom_text: {
    after_submit: null,
    shipping_address: null,
    submit: null,
    terms_of_service_acceptance: null
  },
  customer: 'cus_SZ2WYe5AWaVGKF',
  customer_creation: null,
  customer_details: {
    address: {
      city: null,
      country: 'KR',
      line1: null,
      line2: null,
      postal_code: null,
      state: null
    },
    email: 'johndoeyyd@gmail.com',
    name: 'johhn',
    phone: null,
    tax_exempt: 'none',
    tax_ids: []
  },
  customer_email: null,
  discounts: [],
  expires_at: 1750951770,
  invoice: null,
  invoice_creation: {
    enabled: false,
    invoice_data: {
      account_tax_ids: null,
      custom_fields: null,
      description: null,
      footer: null,
      issuer: null,
      metadata: {},
      rendering_options: null
    }
  },
  livemode: false,
  locale: null,
  metadata: {
    productId: '685c01e14eeb8092e7300640',
    userId: '685c096468359b1216cb3d8b'
  },
  mode: 'payment',
  payment_intent: 'pi_3RdvGjQ4lBhBuMOJ1ayQ7JqW',
  payment_link: null,
  payment_method_collection: 'if_required',
  payment_method_configuration_details: null,
  payment_method_options: { card: { request_three_d_secure: 'automatic' } },
  payment_method_types: [ 'card' ],
  payment_status: 'paid',
  permissions: null,
  phone_number_collection: { enabled: false },
  presentment_details: { presentment_amount: 41138, presentment_currency: 'krw' },      
  recovered_from: null,
  saved_payment_method_options: {
    allow_redisplay_filters: [ 'always' ],
    payment_method_remove: 'disabled',
    payment_method_save: null
  },
  setup_intent: null,
  shipping_address_collection: null,
  shipping_cost: null,
  shipping_options: [],
  status: 'complete',
  submit_type: null,
  subscription: null,
  success_url: 'http://localhost:3000/success?productId=685c01e14eeb8092e7300640&userId=685c096468359b1216cb3d8b',
  total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
  ui_mode: 'hosted',
  url: null,
  wallet_options: null
}
eventType checkout.session.completed
data {
  id: 'ch_3RdvGjQ4lBhBuMOJ148WI5L5',
  object: 'charge',
  amount: 2900,
  amount_captured: 2900,
  amount_refunded: 0,
  application: null,
  application_fee: null,
  application_fee_amount: null,
  balance_transaction: 'txn_3RdvGjQ4lBhBuMOJ1yxUShFC',
  billing_details: {
    address: {
      city: null,
      country: 'KR',
      line1: null,
      line2: null,
      postal_code: null,
      state: null
    },
    email: 'johndoeyyd@gmail.com',
    name: 'dwdwdw dwadwad',
    phone: null,
    tax_id: null
  },
  calculated_statement_descriptor: 'Stripe',
  captured: true,
  created: 1750865390,
  currency: 'usd',
  customer: 'cus_SZ2WYe5AWaVGKF',
  description: null,
  destination: null,
  dispute: null,
  disputed: false,
  failure_balance_transaction: null,
  failure_code: null,
  failure_message: null,
  fraud_details: {},
  livemode: false,
  metadata: {},
  on_behalf_of: null,
  order: null,
  outcome: {
    advice_code: null,
    network_advice_code: null,
    network_decline_code: null,
    network_status: 'approved_by_network',
    reason: null,
    risk_level: 'normal',
    risk_score: 35,
    seller_message: 'Payment complete.',
    type: 'authorized'
  },
  paid: true,
  payment_intent: 'pi_3RdvGjQ4lBhBuMOJ1ayQ7JqW',
  payment_method: 'pm_1RdvGjQ4lBhBuMOJvsdwOzbD',
  payment_method_details: {
    card: {
      amount_authorized: 2900,
      authorization_code: '549879',
      brand: 'visa',
      checks: [Object],
      country: 'US',
      exp_month: 6,
      exp_year: 2028,
      extended_authorization: [Object],
      fingerprint: '4SGERArAYrxykaph',
      funding: 'credit',
      incremental_authorization: [Object],
      installments: null,
      last4: '4242',
      mandate: null,
      multicapture: [Object],
      network: 'visa',
      network_token: [Object],
      network_transaction_id: '528371698265114',
      overcapture: [Object],
      regulated_status: 'unregulated',
      three_d_secure: null,
      wallet: null
    },
    type: 'card'
  },
  presentment_details: { presentment_amount: 41138, presentment_currency: 'krw' },      
  radar_options: {},
  receipt_email: null,
  receipt_number: null,
  receipt_url: 'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xUmRzS1VRNGxCaEJ1TU9KKPGr8MIGMga3yN1uLik6LBaEJmv-yOItCu9-aF1EX9rUDcl0-6eTQgGXZp5L800WHoLrNIKdwE4MVf80',  
  refunded: false,
  review: null,
  shipping: null,
  source: null,
  source_transfer: null,
  statement_descriptor: null,
  statement_descriptor_suffix: null,
  status: 'succeeded',
  transfer_data: null,
  transfer_group: null
}